// Import required types
import { TaskProps, StatusProps, PriorityProps } from "../../types/types";

// Helper function to create dates relative to today
const createDate = (daysOffset: number = 0): Date => {
    const date = new Date();
    date.setDate(date.getDate() + daysOffset);
    return date;
};

// Sample tasks data with a variety of statuses, priorities and due dates
export const sampleTasks: TaskProps[] = [
    {
        id: "1",
        title: "Complete Project Proposal",
        description: "Draft and finalize the project proposal for the new client including timeline and budget estimates.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(5),
    },
    {
        id: "2",
        title: "Weekly Team Meeting",
        description: "Prepare agenda and host weekly team sync to discuss project progress and blockers.",
        status: StatusProps.PENDING,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-1),
        updatedAt: createDate(-1),
        dueDate: createDate(1),
    },
    {
        id: "3",
        title: "Code Review",
        description: "Review pull requests for the authentication feature branch.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-3),
        updatedAt: createDate(0),
        dueDate: createDate(0),
    },
    {
        id: "4",
        title: "Update Documentation",
        description: "Update API documentation with new endpoints and response formats.",
        status: StatusProps.ARCHIVED,
        priority: PriorityProps.LOW,
        createdAt: createDate(-5),
        updatedAt: createDate(-2),
        dueDate: createDate(-1),
    },
    {
        id: "5",
        title: "Client Presentation",
        description: "Prepare and deliver project progress presentation to the client.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-1),
        updatedAt: createDate(-1),
        dueDate: createDate(3),
    },
    {
        id: "6",
        title: "Bug Fix: Login Flow",
        description: "Investigate and fix reported issues with the user login authentication process.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-1),
        updatedAt: createDate(0),
        dueDate: createDate(2),
    },
    {
        id: "7",
        title: "Performance Optimization",
        description: "Analyze and optimize database queries for better application performance.",
        status: StatusProps.PENDING,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(4),
    },
    {
        id: "8",
        title: "User Testing Session",
        description: "Conduct user testing session for the new feature release and gather feedback.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "9",
        title: "Security Audit",
        description: "Perform security audit of the application and document potential vulnerabilities.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-3),
        updatedAt: createDate(0),
        dueDate: createDate(7),
    },
    {
        id: "10",
        title: "Email Template Design",
        description: "Design and implement new responsive email templates for user notifications.",
        status: StatusProps.ARCHIVED,
        priority: PriorityProps.LOW,
        createdAt: createDate(-7),
        updatedAt: createDate(-3),
        dueDate: createDate(-2),
    },
    {
        id: "11",
        title: "Mobile App Development",
        description: "Start development of mobile app version with React Native.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-1),
        updatedAt: createDate(-1),
        dueDate: createDate(14),
    },
    {
        id: "12",
        title: "Database Migration",
        description: "Plan and execute database migration to new cloud infrastructure.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(10),
    },
    {
        id: "13",
        title: "UI/UX Review",
        description: "Conduct comprehensive review of user interface and experience.",
        status: StatusProps.PENDING,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(5),
    },
    {
        id: "14",
        title: "API Integration",
        description: "Integrate third-party payment processing API.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(7),
    },
    {
        id: "15",
        title: "Code Refactoring",
        description: "Refactor legacy code to improve maintainability.",
        status: StatusProps.PENDING,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(8),
    },
    {
        id: "16",
        title: "Automated Testing",
        description: "Implement automated testing suite for core functionality.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-6),
        updatedAt: createDate(-1),
        dueDate: createDate(9),
    },
    {
        id: "17",
        title: "Customer Support Training",
        description: "Conduct training session for customer support team on new features.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-8),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "18",
        title: "Analytics Dashboard",
        description: "Create analytics dashboard for monitoring user engagement.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(12),
    },
    {
        id: "19",
        title: "Content Management System",
        description: "Develop CMS for managing website content.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(15),
    },
    {
        id: "20",
        title: "Server Maintenance",
        description: "Perform routine server maintenance and updates.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "21",
        title: "Social Media Integration",
        description: "Add social media sharing functionality.",
        status: StatusProps.PENDING,
        priority: PriorityProps.LOW,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(6),
    },
    {
        id: "22",
        title: "User Onboarding Flow",
        description: "Design and implement improved user onboarding experience.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(8),
    },
    {
        id: "23",
        title: "Payment Gateway Setup",
        description: "Configure and test new payment gateway integration.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(7),
    },
    {
        id: "24",
        title: "SEO Optimization",
        description: "Implement SEO improvements across website.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(10),
    },
    {
        id: "25",
        title: "Mobile Responsiveness",
        description: "Ensure all pages are fully responsive on mobile devices.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(5),
    },
    {
        id: "26",
        title: "Data Backup System",
        description: "Implement automated data backup system.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-6),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "27",
        title: "User Survey",
        description: "Create and distribute user satisfaction survey.",
        status: StatusProps.PENDING,
        priority: PriorityProps.LOW,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(4),
    },
    {
        id: "28",
        title: "Password Reset Flow",
        description: "Improve password reset functionality and security.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(6),
    },
    {
        id: "29",
        title: "Error Logging",
        description: "Implement comprehensive error logging system.",
        status: StatusProps.PENDING,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(8),
    },
    {
        id: "30",
        title: "Cache Implementation",
        description: "Implement caching system for improved performance.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(9),
    },
    {
        id: "31",
        title: "API Documentation",
        description: "Update API documentation with latest endpoints.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-7),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "32",
        title: "Load Testing",
        description: "Conduct load testing on production servers.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(7),
    },
    {
        id: "33",
        title: "Feature Flags",
        description: "Implement feature flag system for gradual rollouts.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(11),
    },
    {
        id: "34",
        title: "Code Documentation",
        description: "Update code documentation for new features.",
        status: StatusProps.PENDING,
        priority: PriorityProps.LOW,
        createdAt: createDate(-2),
        updatedAt: createDate(-1),
        dueDate: createDate(5),
    },
    {
        id: "35",
        title: "Accessibility Audit",
        description: "Conduct accessibility audit and implement improvements.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(8),
    },
    {
        id: "36",
        title: "Database Optimization",
        description: "Optimize database queries and indexes.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(6),
    },
    {
        id: "37",
        title: "User Feedback System",
        description: "Implement in-app user feedback collection system.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.MEDIUM,
        createdAt: createDate(-3),
        updatedAt: createDate(-1),
        dueDate: createDate(9),
    },
    {
        id: "38",
        title: "SSL Certificate Renewal",
        description: "Renew and update SSL certificates.",
        status: StatusProps.COMPLETED,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-6),
        updatedAt: createDate(-1),
        dueDate: createDate(-1),
    },
    {
        id: "39",
        title: "CI/CD Pipeline",
        description: "Set up continuous integration and deployment pipeline.",
        status: StatusProps.IN_PROGRESS,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-5),
        updatedAt: createDate(-1),
        dueDate: createDate(12),
    },
    {
        id: "40",
        title: "Monitoring Setup",
        description: "Set up application monitoring and alerting system.",
        status: StatusProps.PENDING,
        priority: PriorityProps.HIGH,
        createdAt: createDate(-4),
        updatedAt: createDate(-1),
        dueDate: createDate(10),
    }
];